### ISSUE TITLE
Import data from 4clojure.com

### ISSUE THREAD

**Issue by oxalorg** [oxalorg/4ever-clojure#13]
@humorless has an amazing idea to use a chrome extension to scrape individual data from 4clojure.com 

https://twitter.com/humorless/status/1413907323139936257

I don't know how reliable it is given the fact that 4clojure.com keeps returning 502

But for folks who want to preserve their solutions it's a great idea.

And then we can add a file select button which takes the csv and imports the data into our localStorage.

**Comment by Invertisment** [comment]
First of all: Import to where? And what capabilities will the import have?

The current implementation is static clientside.

What if people could simply use their public repos from github/gitlab/bitbucket? This way you'd be able to find that a person even uses 4ever-clojure.
This wasn't possible with how 4clojure approached things as it stored the things centrally.
Also this would preserve solution improvement histories and allow to simply clone the repository to run the code too.
And there wouldn't be any load on the server.
But there wouldn't be a way to ensure that the solutions are correct before evaluation (I wouldn't really like to run unsafe user code on browsers; fork bomb, oh yes).

I'm not sure if all of these are good features but one thing is to see how a good golfer writes an expression and then it may have more sense to even know how he achieved it.

**Comment by oxalorg** [comment]
All solutions are now visible from the problems. They are anonymized but better than nothing :)
