### ISSUE TITLE
problem 3 not work 

### ISSUE THREAD

**Issue by humorless** [oxalorg/4ever-clojure#2]
Message `Method toUpperCase on function String() { [native code] } not allowed!`

**Comment by borkdude** [comment]
This should already be fixed, but @oxalorg needs to re-deploy the website. Can you do this @oxalorg ?

**Comment by oxalorg** [comment]
Whoops! Deployed the new site :)

**Comment by borkdude** [comment]
Confirmed it works now!

**Comment by borkdude** [comment]
@oxalorg There is a regression of this issue with the new nextjournal clojure-mode stuff.

The solution is to use the config that I added in in [this commit](https://github.com/oxalorg/4ever-clojure/commit/b39941699a95c6bc37c8bb2f746f7bb892b92b2a) to the call to `sci/init` in the new setup.

**Comment by oxalorg** [comment]
Great catch! Thanks, fixed :tada:
