### ISSUE TITLE
Problem 137 uses Java's Integer/MAX_VALUE

### ISSUE THREAD

**Issue by borkdude** [oxalorg/4ever-clojure#24]
<img width="738" alt="Screenshot 2021-07-11 at 14 18 10" src="https://user-images.githubusercontent.com/284934/125194752-e3160980-e252-11eb-913c-f7d526f7645d.png">

Alternative is shown at the bottom of the screenshot.

**Comment by oxalorg** [comment]
js/Number.MAX_VALUE is too big, just changed the test to this instead:

```
(= [16 18 5 24 15 1] (__ 2147483647 42))
```

**Comment by oxalorg** [comment]
On second thought, I changed the test to this:

```
(= [22 6 10 5 0 19 6 9 6 31] (__ js/Number.MAX_SAFE_INTEGER 42))
```
