### ISSUE TITLE
clojure.core/format is not accepted in Problem 16

### ISSUE THREAD

**Issue by k2n** [oxalorg/4ever-clojure#35]
[https://4clojure.oxal.org/#/problem/16](https://4clojure.oxal.org/#/problem/16)

```
#(format "Hello, %s!" %)
```

is one of \[the accepted solutions\](https://4clojure.oxal.org/#/problem/16/solutions) but I see the following error. 

```
#error {:message "Could not resolve symbol: format", :data {:type :sci/error, :line 1, :column 7, :file nil, :phase "analysis"}} 
```

It works on regular `bb`. 

```
Babashka v0.3.1 REPL.
Use :repl/quit or :repl/exit to quit the REPL.
Clojure rocks, Bash reaches.

user=> (format "Hello, %s!" "Kenji")
"Hello, Kenji!"
```

Is it possible to run the tests against the solutions archive?

**Comment by borkdude** [comment]
This is because ClojureScript doesn't have `format` in the way that Clojure has it. We could fake it by shimming it with `goog.string/format`. I think the solutions need some curation. Perhaps some of them should not be shown if they don't work in this environment.

**Comment by oxalorg** [comment]
I think we should add a note somewhere that this is clojurescript and expect some things to not be "exactly" the same as before. 

Maybe start documenting some of these gotchas (and a list of common clj -> cljs functions)

**Comment by borkdude** [comment]
I'm looking at this now.
