### ISSUE TITLE
Problem 125 is trivial and not as in 4clojure

### ISSUE THREAD

**Issue by Invertisment** [oxalorg/4ever-clojure#36]
The original from 4clojure.com is this:
```
(= (str '__) (__))
```
The current one expects a function of two arguments and is badly formatted too:
```
(= (__ '(fn [x] (__ x x))
                            '(fn [x] (__ x x)))
                       ((fn [x] (__ x x))
                        '(fn [x] (__ x x))))
```
And it means that `=` is allowed in the new "complicated" version and not in the original version.
Does this mean that all problems are now different?

It was hard in the original, now it's trivial as one symbol will solve it.

**Comment by oxalorg** [comment]
Thank you for the bug report! I've fixed this, will test if a solution works locally and then deploy it :)
