### ISSUE TITLE
Could not use `Character/isUpperCase` in problem #29

### ISSUE THREAD

**Issue by hikrr** [oxalorg/4ever-clojure#38]
I find `Character/isUpperCase` is not working(some solutions use it though).
I wonder is every java interop not acceptable in the editor?

![image](https://user-images.githubusercontent.com/80665253/126125304-ceae2b34-1cb7-4ebf-9985-8990e9f59869.png)

```
(fn [s]
    (apply str (filter #(Character/isUpperCase %) s)))
```

**Comment by borkdude** [comment]
This environment runs in JavaScript, directly in your browser. So not all Java interop works, but some of it is the same in JS if you're lucky.

**Comment by oxalorg** [comment]
Added a note/warning on home page: 9bc5f1014189920e5e61188034834493a32e5fbb

**Comment by borkdude** [comment]
The problems should probably be edited on a case by case basis.

**Comment by hikrr** [comment]
Thanks for all your reply!!
