### ISSUE TITLE
scrape problems difficulty

### ISSUE THREAD

**Issue by humorless** [oxalorg/4ever-clojure#4]
scraping by Chrome Extension listly.io
[LISTLY_new.xlsx](https://github.com/oxalorg/4ever-clojure/files/6783923/LISTLY_new.xlsx)

**Comment by oxalorg** [comment]
Thanks this is super helpful, I'll write a small babashka function to read the csv then rewrite the problem data using rewrite-clj

**Comment by borkdude** [comment]
Babashka now also comes with rewrite-clj btw :)
