### ISSUE TITLE
Getting a wrong feedback after solving more than one task

### ISSUE THREAD

**Issue by ArielA147** [oxalorg/4ever-clojure#44]
#### Description
Getting a wrong feedback of `oh-no` although the solution is correct to the current task, after solving more than one task,.
It thinks that the solution is still the the solution you wrote to the previous task.

#### To Reproduce
1. Answer correct on a question and clicking `run` to check the solution, you will get `complete!`.
2. Move to the next question
- The previous answer automatic be shown on the window where you type the answer.
3.  Write the correct answer to the new question and run the solution.
4. You will get an `oh-no`, which means that your answer is wrong although it is correct.

this happens both when navigation by changing the url and using the popup of the solution.

#### Work around
A hard reset to the browser every-time you move to a new question.

**Comment by oxalorg** [comment]
Looks like this might be fixed in the latest build. Can you check this out one more time on https://4clojure.oxal.org/

**Comment by ArielA147** [comment]
![problem solved](https://media.giphy.com/media/5z0cCCGooBQUtejM4v/giphy.gif)

**Comment by ArielA147** [comment]
![problem solved](https://media.giphy.com/media/5z0cCCGooBQUtejM4v/giphy.gif)
