### ISSUE TITLE
deduplicate solutions

### ISSUE THREAD

**Issue by borkdude** [oxalorg/4ever-clojure#55]
There are a lot of double solutions here:

https://4clojure.oxal.org/#/problem/2/solutions

Perhaps the front-end could deduplicate.

**Comment by oxalorg** [comment]
Maybe it might be better to just do it at source. The files are too heavy anyways, wrote a quick bb script deploying the changes now! https://github.com/oxalorg/4clojure-solutions-archive/commit/d4baa80de4272dcc717e5d2e18cd54e5b4214c7d

**Comment by oxalorg** [comment]
https://4clojure.oxal.org/#/problem/2/solutions

Yup looks like it worked! 🌸

**Comment by borkdude** [comment]
Very nice!
