### ISSUE TITLE
Modal doesn't work on mobile

### ISSUE THREAD

**Issue by Invertisment** [oxalorg/4ever-clojure#61]
When I try to solve anything on mobile then modal takes the wrong part of the screen.
Why do you want to have that modal at all? Why not display the result inline as the original 4clojure did? It simply worked.

For instance in this screenshot (from my phone) I don't see the result and I can't close the modal because the button it outside of the screen. 

This also makes so that you can't simply run commands in the REPL and only when you're happy then you send them to evaluate for the test check. This also hides the results so that you won't be able to see them when you type your code.

Screenshot:
![image](https://user-images.githubusercontent.com/1641263/183348357-36ca0270-0305-4b9c-b9d1-19d9d1fa5dc8.png)

**Comment by Invertisment** [comment]
I added PR https://github.com/oxalorg/4ever-clojure/pull/62 to cap the width of the modal and now it looks like this (rough for the long problems but it's at least something):

![image](https://user-images.githubusercontent.com/1641263/183351555-cc277748-f5be-4d48-84de-3d91ce046e18.png)

**Comment by borkdude** [comment]
> Why do you want to have that modal at all? 

I agree that we should not show a modal at all if we don't have to.

**Comment by Invertisment** [comment]
Your comment is ambiguous.
I think that there should be a button to evaluate and to "attempt". And I don't think that those buttons should show any modals.
But if they show then those modals should be at least readable on all devices.

What did you try to propose?

**Comment by borkdude** [comment]
I've made a remark to @oxalorg before that I didn't like the modal either and would rather see it removed. I'm not sure if he agrees. Ultimately @oxalorg is in charge of the UI, so I'll let him comment :)

**Comment by Invertisment** [comment]
Alright. Well if he decides to keep the modal then I think my PR should be merged.

**Comment by oxalorg** [comment]
I 💯 agree with both of y'all! Maybe it's time to get rid of the modal completely! :)
