### ISSUE TITLE
get rid of js/alerts

### ISSUE THREAD

**Issue by oxalorg** [oxalorg/4ever-clojure#7]
It's not 2002. Llet's show some style, some sugar, and a bit of sass!

**Comment by CoderPrans** [comment]
Hey, I am woking on the results display modal. When "Run" is clicked. 

This also addresses #15 

![Screenshot at 2021-07-11 19-01-24](https://user-images.githubusercontent.com/24974089/125197286-a0682780-e27a-11eb-867c-cc101a5303f8.png)
