### ISSUE TITLE
Site is not loading

### ISSUE THREAD

**Issue by costacamila** [oxalorg/4ever-clojure#75]
When trying to access I'm getting:

This site can’t be reached4clojure.oxal.org took too long to respond.
ERR_CONNECTION_TIMED_OUT

Can you please check it out?

**Comment by borkdude** [comment]
@oxalorg ?

**Comment by borkdude** [comment]
@costacamila I managed to set up a back up instance here, for the time being: 

https://borkdude.github.io/4ever-clojure/

**Comment by borkdude** [comment]
It seems the site is back up, thanks @oxalorg !

https://4clojure.oxal.org/

**Comment by costacamila** [comment]
thank you so much!!!
