### ISSUE TITLE
Evaluation of wrong arity code results in `pass`

### ISSUE THREAD

**Issue by Invertisment** [oxalorg/4ever-clojure#78]
The UI check or eval function is bad because on error (let's say we call `([inc] 1 2 3 4 5)`) the custom eval returns a string:

```
(defn eval-string [source]
  (try (sci/eval-string* context source)
       (catch :default e
         (with-out-str (error-handler source e)))))
```
This is the code from current version.

Repro:
Go to https://4clojure.oxal.org/#/problem/38 (it will call user's code with multiple args)
Enter `[]` into the field
Outcome: pass fail pass

A quickfix of `if (true? passed?)` works when presenting the data but this probably needs to be decided in a better way.

It would be a basic refactoring into some kind of a map or similar thing but this function is used all over the place.

**Comment by borkdude** [comment]
I think it would be better indeed to return a map or vector with `[:succes ...]`, `[:error ..]`

**Comment by Invertisment** [comment]
This issue is related to this one:
https://github.com/oxalorg/4ever-clojure/issues/70

It happens like this because the evaluator returns string and it's neither `true?` nor `false?`. So there are no failed or succeeded tests and the state is saved with zeros.

**Comment by borkdude** [comment]
Well spotted!
