### ISSUE TITLE
improve code input box

### ISSUE THREAD

**Issue by oxalorg** [oxalorg/4ever-clojure#9]
- [ ] line numbers would be cool
- [ ] code highlighting? even better
- [ ] auto indenting? or maybe indents with tabs

![image](https://user-images.githubusercontent.com/4194289/125118054-c8397d00-e10c-11eb-98fe-6c1c42e8911d.png)

Yeah linting won't work as we do fill in the blanks :see_no_evil:

**Comment by bolivier** [comment]
I'd be down to work on this.  Is there a specific UI somewhere you had in mind?

**Comment by borkdude** [comment]
It might be nice to use clojure-mode as the highlighting tool. It even supports paredit I believe. See a demo (also with SCI) here:

https://nextjournal.github.io/clojure-mode/

**Comment by oxalorg** [comment]
I was actually just checking that. Although "ace editor" PR has already been merged into master. I think I'll give it a try and see if that works.

**Comment by oxalorg** [comment]
Migrated editor to CodeMirror + https://github.com/nextjournal/clojure-mode in 6d9b0d0179c583978c246b0e88eed947523aadf3

![image](https://user-images.githubusercontent.com/4194289/125177620-ef6e7800-e1fa-11eb-809b-ce4d28e7d80e.png)

Super sorry @bolivier your code stayed in only for a couple of hours :raised_hands: !

 This version has super handy shortcuts and local eval for testing!!
