### ISSUE TITLE
Add a button for formatting code alongside "Run" and "Settings"

### ISSUE THREAD

**Issue by migraine-user** [oxalorg/4ever-clojure#93]
and perhaps a keyboard shortcut!
When I am going through a problem, it's hard to iterate on the browser while formatting it so I can mentally parse it. It would be nice to have a way to format the code that I was writing so far.
Maybe it would be possible to use [cljfmt](https://github.com/weavejester/cljfmt) for this? I am still new to clojure, but I think I can try implementing this myself if that's alright.

**Comment by borkdude** [comment]
clojure-mode, which is the library used in this project also supports formatting.

You can see this at work in this playground, formatting happens when you hit tab:

https://squint-cljs.github.io/squint/

**Comment by migraine-user** [comment]
Oh, there wouldn't be a need for a new library. Is formatting available on the website as it is now, or would that still need to be added with clojure-mode?

**Comment by oxalorg** [comment]
Fixed in #95
