### ISSUE TITLE
A "Sign In" option would be nice to track solutions across multiple platforms

### ISSUE THREAD

**Issue by jdjohnston** [oxalorg/4ever-clojure#96]
It would be a nice enhancement for a user to be able to work on these on more than one platform (say, phone & laptop) and still have the home page show _all_ solutions for the signed-in user. If I had the option, I would sign in once on each platform, maybe by way of GitHub, & hopefully the website would then "remember" me on later visits, no matter what platform I was using.

BTW, I remember working on these on the original `4clojure` website, some years ago. Very cool to see these again. Thanks!

**Comment by oxalorg** [comment]
Great feature idea, but this is not going to be supported as we want this to be able to run forever with no backend / db / state.

An alternative solution I can think of right now is to allow localStorage import/export, or read/write to a gist, or something like that so people can sync it themselves

**Comment by oxalorg** [comment]
More ideas are welcome! :)

**Comment by Invertisment** [comment]
Could it import the whole 4clojure archive? This way there could be a way to compare as in the original.

I don't remember already -- how much does it weigh?

It could also just save the local ones into local storage but compare the "present solutions" from a static page. This would avoid the import and additional steps for new users.

**Comment by oxalorg** [comment]
We already do that :) https://4clojure.oxal.org/#/problem/7/solutions

**Comment by Invertisment** [comment]
Ah, those aren't that interesting because there are no nicknames. Oh well. But hey, it works.
